server:
  port: ${PORT:8080}
  servlet:
    context-path: "/api/v1"

spring:
  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: update # use this autocreate database if it is embeded
  jackson:
    serialization:
      fail-on-empty-beans: false
