spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${DB_HOST:localhost}:5432/demo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    # data: classpath:/data.sql
    continue-on-error: false